"""MENSAJE

Revision ID: 7747f953eca1
Revises: 
Create Date: 2024-01-25 19:32:35.412336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7747f953eca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle', sa.Text(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('predeterminada', sa.Boolean(), nullable=True),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direcciones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
